### ISSUE TITLE
请问使用的redis集群是什么方案？

### ISSUE THREAD

**Issue by Isarg** [Johor03/redis_generator_id#2]
使用redis-cluster，连接到任意一台redis都会根据key找到对应的redis，不需要每台redis设置初始值和步长

**Comment by Johor03** [comment]
使用redis-cluster需要可不涉及分片或步长，但是要考虑redis 主从集群的lua执行更新问题

**Comment by worlse** [comment]
哪里设置访问redis的库,不想都放在第一个库

**Comment by Johor03** [comment]
> 哪里设置访问redis的库,不想都放在第一个库

cluster_redis_config.default.properties 这个是默认的配置文件，你可以在项目中依赖并且覆盖该配置。配置文件名叫：cluster_redis_config.properties，配置文件内容参考default配置文件格式
